name: ichan
version: 1.20.9211316+1195
publish_to: none
description: Forum reader
environment:
  sdk: ">=2.9.0 <3.0.0"
dependencies:
  async: ^2.4.1
  http: ^0.12.1
  dio: ^3.0.9
  rxdart: ^0.24.0
  bloc: ^6.0.0
  flutter_bloc: ^6.0.0
  flutter_cache_manager: ^1.4.1
  intl: 0.16.1
  provider: ^4.1.1
  hive: ^1.4.1+1
  hive_flutter: ^0.3.0
  collection: ^1.14.13
  equatable: ^1.2.0
  font_awesome_flutter: ^8.8.0
  flutter_icons: ^1.1.0
  cupertino_toolbar: ^1.0.0
  cupertino_icons: ^0.1.3
  shimmer: ^1.1.0
  video_player: ^0.10.10
  flutter_vlc_player:
    git: git@github.com:solid-software/flutter_vlc_player.git
  chewie: ^0.9.10
  flutter_html:
    git: git@github.com:Zchandev/flutter_html.git
  extended_image: ^1.1.1
  path_provider: ^1.6.11
  package_info: ^0.4.0+16
  device_info: ^0.4.2+4
  scrollable_positioned_list: ^0.1.6
  file_picker: ^1.12.0
  mime_type: ^0.3.1
  url_launcher: ^5.4.11
  get_it: ^4.0.2
  firebase_core: ^0.5.0
  firebase_analytics: ^6.0.0
  firebase_crashlytics: ^0.1.4+1
  simple_animations: ^2.2.1
  video_thumbnail: ^0.2.2
  universal_html: ^1.2.3
  wc_flutter_share: ^0.2.2
  permission_handler: ^5.0.1+1
  # audioplayers: ^0.15.1
  disk_space: ^0.0.3
  flutter_secure_storage: ^3.3.3
  retry: ^3.0.1
  # flutter_apns:
  #   git: git@github.com:FloPMT/flutter-apns.git
  pull_to_refresh: ^1.6.2
  flutter_slidable: ^0.5.4
  cookie_jar: ^1.0.0
  dio_cookie_manager: ^1.0.0
  flutter_inappwebview: ^4.0.0+4
  gallery_saver: ^2.0.1
  image_gallery_saver: ^1.5.0
  youtube_player_flutter: ^7.0.0+7
  # render_metrics: ^1.0.1
  ota_update: ^2.4.1
  flutter_hooks: ^0.13.1
  flutter_image_compress: ^0.7.0
  exif: ^1.0.3
  receive_sharing_intent: ^1.4.1
  flutter_statusbar_manager: ^2.0.0
  easy_localization: 2.3.3
  directory_picker: ^1.0.0
  flutter:
    sdk: flutter
dev_dependencies:
  pedantic: ^1.9.0
  flutter_launcher_icons: ^0.7.3
  flutter_native_splash: ^0.1.9
  hive_generator: ^0.7.0+2
  build_runner: ^1.8.0
  # moor_generator: any
  # test: any
  # flutter_test:
  #   sdk: flutter
  # flutter_driver:
  #   sdk: flutter
dependency_overrides:
  permission_handler: ^5.0.1+1
  flutter_svg: ^0.18.0
  intl: ^0.16.1
  path: 1.7.0
flutter:
  uses-material-design: true
  assets:
    - assets/translations/
flutter_icons:
  android: launcher_icon
  image_path: assets/icon/icon.png
  ios: true
flutter_native_splash:
  image: assets/images/splash2.png
  color: "000000"
